<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.emergent.javaformat</groupId>
    <artifactId>emergent-java-format-parent</artifactId>
    <version>3.0.0-SNAPSHOT</version>
  </parent>

  <artifactId>emergent-java-format-native</artifactId>
  <name>emergent-java-format-native</name>
  <description>Emergent Java Format</description>

  <properties>
    <nativeImageName>emergent-java-format-${os.name}_${os.arch}</nativeImageName>
    <!--
    <nativeBinary>${org.emergent.javaformat:emergent-java-format-native:bin:native}</nativeBinary>
    -->
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.emergent.javaformat</groupId>
      <artifactId>emergent-java-format</artifactId>
      <version>${project.version}</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.emergent.javaformat</groupId>
      <artifactId>emergent-java-format-spi</artifactId>
      <version>${project.version}</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-toolchains-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>select-jdk-toolchain</goal>
            </goals>
            <configuration>
              <version>[23)</version>
              <vendor>GraalVM Community</vendor>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.graalvm.buildtools</groupId>
        <artifactId>native-maven-plugin</artifactId>
        <version>0.11.6-SNAPSHOT</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <id>build-native</id>
            <goals>
              <goal>compile-no-fork</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <verbose>true</verbose>
              <fallback>false</fallback>
              <enforceToolchain>true</enforceToolchain>
              <mainClass>${mainClass}</mainClass>
              <imageName>${nativeImageName}</imageName>
              <configFiles>
                <configFile>${project.basedir}/src/main/resources/META-INF/native-image</configFile>
              </configFiles>
              <buildArgs>
                <buildArg>-H:+UnlockExperimentalVMOptions</buildArg>
                <buildArg>-H:+IncludeAllLocales</buildArg>
                <buildArg>-H:+ReportExceptionStackTraces</buildArg>
                <buildArg>-H:-UseContainerSupport</buildArg>
                <buildArg>-march=compatibility</buildArg>
                <buildArg>--exact-reachability-metadata</buildArg>
                <buildArg>--initialize-at-build-time=com.sun.tools.javac.file.Locations</buildArg>
              </buildArgs>
              <jvmArgs>
                <jvmArg>--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED</jvmArg>
                <jvmArg>--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED</jvmArg>
                <jvmArg>--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED</jvmArg>
                <jvmArg>--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED</jvmArg>
                <jvmArg>--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED</jvmArg>
                <jvmArg>--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED</jvmArg>
                <jvmArg>--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED</jvmArg>
              </jvmArgs>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-install-plugin</artifactId>
        <executions>
          <execution>
            <id>default-install</id>
            <configuration>
              <skip>true</skip>
            </configuration>
          </execution>
          <execution>
            <id>local-install</id>
            <goals>
              <goal>install-file</goal>
            </goals>
            <phase>pre-integration-test</phase>
            <configuration>
              <groupId>${project.groupId}</groupId>
              <artifactId>${project.artifactId}</artifactId>
              <version>${project.version}</version>
              <classifier>native</classifier>
              <extension>exe</extension>
              <packaging>bin</packaging>
              <file>${project.build.directory}/${nativeImageName}</file>
              <localRepositoryPath>${localTestRepositoryPath}</localRepositoryPath>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <!--
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>attach-native</id>
            <phase>package</phase>
            <goals>
              <goal>attach-artifact</goal>
            </goals>
            <configuration>
              <artifacts>
                <artifact>
                  <file>${project.build.directory}/${nativeImageName}</file>
                  <classifier>native</classifier>
                  <type>bin</type>
                </artifact>
              </artifacts>
            </configuration>
          </execution>
        </executions>
      </plugin>
      -->
      <!--
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>properties</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>script-chmod</id>
            <phase>install</phase>
            <goals>
              <goal>exec</goal>
            </goals>
            <configuration>
              <executable>chmod</executable>
              <arguments>
                <argument>+x</argument>
                <argument>${nativeBinary}</argument>
              </arguments>
            </configuration>
          </execution>
        </executions>
      </plugin>
      -->
    </plugins>
  </build>
</project>
