import org.apache.tools.ant.taskdefs.ExecuteJava
import org.gradle.kotlin.dsl.annotationProcessor
import org.gradle.kotlin.dsl.compileOnly
import sun.jvmstat.monitor.MonitoredVmUtil.jvmArgs

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

tasks {
    // Set the JVM compatibility versions
    withType<JavaCompile> {
        sourceCompatibility = "21"
        targetCompatibility = "21"
    }
}
//sourceSets {
//    main {
//        java {
//            srcDirs("src/main/java", "build/generated/sources/annotationProcessor/java/jmh")
//        }
//    }
//}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    annotationProcessor("com.google.auto.service:auto-service:1.1.1")
    annotationProcessor("org.derive4j:derive4j:1.1.1")
    //annotationProcessor("org.immutables:value:${libs.versions.org.immutables.value}")
    annotationProcessor("org.immutables:value:2.12.1")

    compileOnly("org.immutables:value-annotations:2.12.1")

    api(libs.com.fasterxml.jackson.core.jackson.core)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.guava)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jdk8)
    api(libs.com.fasterxml.jackson.module.jackson.module.parameter.names)
    api(libs.com.google.auto.service.auto.service)
    api(libs.com.google.auto.service.auto.service.annotations)
    api(libs.com.google.code.findbugs.jsr305)
    api(libs.com.google.errorprone.error.prone.annotations)
    api(libs.com.google.guava.guava)
    api(libs.derive4j.annotation)
    api(libs.org.functionaljava.functionaljava)
    //api(libs.org.immutables.value)
    //api(libs.org.immutables.annotations)
    api(libs.org.jspecify.jspecify)

    //compileOnly(libs.org.immutables.annotations)

    //annotationProcessor(libs.com.google.auto.service.auto.service)
    //annotationProcessor(libs.org.derive4j.derive4j.annotation)
    //annotationProcessor(libs.org.immutables.value)
    //implementation("org.immutables:value:2.12.1")
    //annotationProcessor("org.immutables:value:2.12.1")


    testImplementation(libs.com.google.truth.truth)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
    testImplementation(libs.org.slf4j.slf4j.simple)

}

group = "org.emergent.javaformat"
version = "3.0.0-SNAPSHOT"
description = "java-format"
//java.sourceCompatibility = JavaVersion.VERSION_21


var gjfRequiredJvmArgs = listOf(
    "--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED",
    "--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED",
    "--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED",
    "--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED",
    "--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED",
    "--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED",
)

tasks {
    withType<JavaCompile> {
        //options.compilerArgs.addAll(gjfRequiredJvmArgs)
        options.compilerArgs.add("-Xlint:unchecked")
        options.compilerArgs.addAll(gjfRequiredJvmArgs)
        //options.compilerArgumentProviders.add(CommandLineArgumentProvider { gjfRequiredJvmArgs })
        //jvmar += CommandLineArgumentProvider { gjfRequiredJvmArgs }
    }


    //runIde {
    //    jvmArgumentProviders += CommandLineArgumentProvider { gjfRequiredJvmArgs }
    //}
}

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}

java {
    withSourcesJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
        artifact(testsJar)
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.withType<AbstractTestTask>().configureEach {
    failOnNoDiscoveredTests = false
}